# include "config/convolutional/lossl_coord/kitti_ford.yaml"

model_module_path: models.convolutional.lossl_coord_int
model:
  skip_top_scales_num: 0


test:
  from_ckpt: weights/convolutional/lossl_coord/kitti_ford_int.pt
  dataset:
    resolution: 65536
    ply_file_coord_scaler: 0.25
