# include "config/convolutional/lossl_coord/kitti_ford.yaml"

model:
  skip_top_scales_num: 0
  quantize_param: True
  int_param_save_path: weights/convolutional/lossl_coord/kitti_ford_int.pt


test:
  from_ckpt: weights/convolutional/lossl_coord/kitti_ford.pt
  dataset:
    test_filelist_path: train_list.txt
    list_sampling_interval: 100
    ply_file_test_filelist_path: train_list.txt
    ply_list_sampling_interval: 50
