model_module_path: models.convolutional.lossl_coord


train:
  rundir_name: 'train_convolutional_<autoindex>'
  batch_size: 8
  num_workers: 8
  optimizer: AdamW
  momentum: 0.9
  weight_decay: 0.0001
  max_grad_norm: 1.0

  ema: True
  ema_warmup: True
  ema_warmup_gamma: 1.0
  ema_warmup_power: 0.8

  learning_rate: 0.0001
  epochs: 60

  scheduler: Step
  lr_step_size: 60
  lr_step_gamma: 0.3

  ckpt_frequency: 5
  test_frequency: 0

  dataset_module_path: 'lib.datasets.KITTIOdometry'
  dataset:
    random_flip: True
    morton_sort: True
    morton_sort_inverse: True
    resolution: 65536


test:
  num_workers: 8
  dataset_module_path: 'lib.datasets.KITTIOdometry'
  dataset:
    morton_sort: False
    resolution: 65536
