# include "config/convolutional/lossy_coord_lossy_color/baseline_r4.yaml"

model:
  encoder_channels: [32, 64, 128, 128]
  decoder_channels: [128, 64, 32]
  geo_lossl_if_sample: [0, 1, 0, 1, 0, 1, 0, 1]
  geo_lossl_channels: [128, 128, 128, 128, 128, 128, 128, 128, 1]
  bits_loss_factor: 4.0
  coord_recon_loss_factor: 1.0
  color_recon_loss_factor: 0.02
