model_path: models.baseline
train:
  rundir_name: 'train_-1'
  device: '0,1'
  batch_size: 64
  epochs: 200
  ckpt_frequency: 9
  lr_step_size: 20
  lr_step_gamma: 0.3
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.005
model:
  input_points_num: 2048
dataset:
  input_points_num: 2048