model_path: models.exp4
train:
  rundir_name: 'train_<autoindex>'
  device: '3'
  batch_size: 8
  weight_decay: 0.0001
  epochs: 100
  ckpt_frequency: 5
  lr_step_size: 20
  lr_step_gamma: 0.1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.001
  test_frequency: 0
  dataset:
    root: 'datasets/modelnet40_manually_aligned'
    input_points_num: 32768
test:
  batch_size: 8
model:
  input_points_num: 32768
