model_path: models.exp0
train:
  rundir_name: 'train_-1'
  device: '0,1,2'
  batch_size: 24
  epochs: 200
  ckpt_frequency: 9
  lr_step_size: 30
  lr_step_gamma: 0.1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.005
model:
  input_points_num: 8192
dataset:
  input_points_num: 8192