model_path: models.exp4
train:
  rundir_name: 'train_<autoindex>'
  device: '2,3'
  batch_size: 32
  epochs: 200
  ckpt_frequency: 10
  lr_step_size: 10
  lr_step_gamma: 0.3
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.005
model:
  input_points_num: 8192
dataset:
  input_points_num: 8192