model_path: models.convolutional.PCGCv2
train:
  rundir_name: 'train_convolutional_<autoindex>'
  device: '3'
  amp: False
  batch_size: 16
  epochs: 100
  ckpt_frequency: 10
  lr_step_size: 20
  lr_step_gamma: 0.1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.01
dataset:
  input_points_num: 8192
  resolution: 128
