model_path: models.convolutional.PCGCv2
train:
  rundir_name: 'train_convolutional_<autoindex>'
  device: '3'
  amp: False
  batch_size: 8
  optimizer: adam
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 20
  ckpt_frequency: 2
  lr_step_size: 4
  lr_step_gamma: 0.5
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.0005
  test_frequency: 2
  dataset_path: 'lib.datasets.ShapeNetCorev2'
test:
  batch_size: 1
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel'
  log_frequency: 1
  dataset:
    root: ['datasets/MVUB', 'datasets/8iVFBv2', 'datasets/Owlii']
    filelist_path: 'list.txt'
    file_path_pattern: '**/*.ply'

    with_color: False
    with_normal: False
    with_file_path: True

    ori_resolution: [512, 1024, 2048]
    resolution: [512, 1024, 2048]


