model_path: models.exp4
train:
  rundir_name: 'train_<autoindex>'
  device: '3'
  batch_size: 64
  num_workers: 4
  optimizer: 'sgd'
  epochs: 100
  momentum: 0.9
  ckpt_frequency: 5
  lr_step_size: 20
  lr_step_gamma: 0.1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  learning_rate: 0.001
  test_frequency: 0
test:
  batch_size: 64
model:
  input_points_num: 4096
dataset:
  input_points_num: 4096