model_path: models.exp4


train:
  rundir_name: 'train_<autoindex>'
  device: '3'
  batch_size: 16
  num_workers: 4
  optimizer: adam
  momentum: 0.9
  weight_decay: 0.0001
  max_grad_norm: 1.0

  learning_rate: 0.0005
  epochs: 20

  ckpt_frequency: 2
  lr_step_size: 4
  lr_step_gamma: 0.5
  resume_from_ckpt: 'runs/train_0/ckpts/epoch_<maxindex>.pt'
  resume_items: ['state_dict']
  test_frequency: 2

  dataset_path: 'lib.datasets.ShapeNetCorev2'
  dataset:
    data_format: '.obj'
    points_num: 50000
    resolution: 0


test:
  batch_size: 1
  num_workers: 2
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel'
  log_frequency: 1
  dataset:
    root: ['datasets/Owlii', 'datasets/8iVFBv2', 'datasets/MVUB']
    filelist_path: 'list.txt'
    file_path_pattern: '**/*.ply'

    with_color: False
    with_normal: False
    with_file_path: True

    ori_resolution: [2048, 1024, 512]
    resolution: [0, 0, 0]

    with_resolution: False
    with_ori_resolution: True

