model_path: models.convolutional.lossy_coord
model:
  basic_block_type: 'InceptionResBlock'
  basic_block_num: 3
  use_batch_norm: False
  activation: 'relu'
  compressed_channels: 8
  encoder_channels: [4, 16, 64, 64]
  decoder_channels: [64, 16, 4]
  coord_recon_loss_type: 'BCE'
  adaptive_pruning: True
  adaptive_pruning_num_scaler: 1.0
  bpp_loss_factor: 0.3
  warmup_steps: 1000
  warmup_bpp_loss_factor: 0.01


train:
  rundir_name: 'train_convolutional_<autoindex>'
  amp: False
  more_reproducible: True
  batch_size: 8
  num_workers: 2
  optimizer: [AdamW, Adam]
  momentum: 0.9
  weight_decay: [0.0001, 0.0]
  max_grad_norm: [1.0, 0.0]

  learning_rate: [0.0005, 0.005]
  epochs: 40

  scheduler: Step
  lr_step_size: 12
  lr_step_gamma: 0.3

  ckpt_frequency: 1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  test_frequency: 4

  dataset_path: 'lib.datasets.ShapeNetCorev2'
  dataset:
    train_filelist_path: 'train_list_obj.txt'
    data_format: '.obj'
    mesh_sample_points_num: 2500000
    mesh_sample_point_method: 'uniform'
    mesh_sample_point_resolution: 256
    random_rotation: True


test:
  batch_size: 1
  num_workers: 2
  log_frequency: 1
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel.Owlii_8iVFBv2_MVUB'
  dataset:
    kd_tree_partition_max_points_num: 0
