model_path: models.convolutional.lossy_coord_lossy_color
model:
  basic_block_type: 'ResBlock'
  basic_block_num: 1
  use_batch_norm: False
  activation: 'relu'
  compressed_channels: [1, 2, 2, 2, 2, 2, 2, 2]
  bottleneck_scaler: 1
  prior_indexes_scaler: 0.0
  prior_indexes_range: [1024, 1024]
  encoder_channels: [32, 64]
  decoder_channels: 32
  geo_lossl_part_channels: [128, 128, 128, 128, 128, 128, 128, 128]
  lossless_coord_indexes_range: [1024, 1024]
  lossless_fea_num_filters: [1, 3, 3, 1]
  bpp_loss_factor: 1.0
  adaptive_pruning: True
  adaptive_pruning_num_scaler: 1.0
  coord_recon_loss_factor: 0.001
  color_recon_loss_factor: 0.2
  warmup_steps: 5000
  warmup_bpp_loss_factor: 0.00001
  linear_warmup: True


train:
  rundir_name: 'train_convolutional_<autoindex>'
  more_reproducible: True
  amp: False
  find_unused_parameters: False
  batch_size: 4
  num_workers: 1
  optimizer: [AdamW, AdamW, AdamW, Adam]
  momentum: 0.9
  weight_decay: [0.0001, 0.0001, 0.0001, 0.0]
  max_grad_norm: [1.0, 1.0, 1.0, 0.0]

  learning_rate: [0.001, 0.0006, 0.0002, 0.005]
  epochs: 350

  scheduler: Step
  lr_step_size: 55
  lr_step_gamma: 0.3

  resume_from_ckpt: ''
  resume_items: ['state_dict']
  log_frequency: 10
  ckpt_frequency: 35
  test_frequency: 35

  dataset_path: 'lib.datasets.PlyVoxel.8iVFBv2'
  dataset:
    filelist_path: 'list_longdress_soldier_all.txt'
    kd_tree_partition_max_points_num: 200000
    with_color: True
    random_rotation: False
    random_flip: False
    random_rgb_perm: False


test:
  batch_size: 1
  num_workers: 0
  log_frequency: 1
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel.MPEG_GPCC_CTC_Solid'
  dataset:
    root: ['datasets/MPEG_GPCC_CTC/Solid']
    filelist_path: ['Solid_1024.txt']
    kd_tree_partition_max_points_num: 0
    with_color: True
    ori_resolution: 1024
    resolution: 1024
