model_path: models.convolutional.lossy_coord_lossy_color
model:
  activation: 'prelu'
  compressed_channels: [1]
  bottleneck_scaler: 2
  encoder_channels: [32, 64]
  decoder_channels: 32
  adaptive_pruning: True
  adaptive_pruning_scaler_train: 1.01
  adaptive_pruning_scaler_test: 1.00
  geo_lossl_if_sample: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
  geo_lossl_channels: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 1]
  bits_loss_factor: 1.0
  coord_recon_loss_factor: 0.4
  color_recon_loss_factor: 0.2
  warmup_fea_loss_steps: 5000
  warmup_color_loss_steps: 5000
  warmup_fea_loss_factor: 0.00001
  warmup_color_loss_factor: 0.00001
  linear_warmup: True


train:
  rundir_name: 'train_convolutional_<autoindex>'
  more_reproducible: True
  amp: False
  find_unused_parameters: False
  batch_size: 4
  num_workers: 4
  optimizer: [AdamW, AdamW, AdamW]
  momentum: 0.9
  weight_decay: [0.00001, 0.00001, 0.0]
  max_grad_norm: 1.0

  learning_rate: [0.002, 0.0006, 0.0002]
  epochs: 350

  scheduler: Step
  lr_step_size: 55
  lr_step_gamma: 0.3

  resume_from_ckpt: ''
  resume_items: ['state_dict']
  log_frequency: 10
  ckpt_frequency: 10
  test_frequency: 10

  dataset_path: 'lib.datasets.PlyVoxel.8iVFBv2'
  dataset:
    filelist_path: 'list_longdress_soldier_all.txt'
    kd_tree_partition_max_points_num: 120000
    with_color: True
    random_rotation: False
    random_flip: True
    random_rgb_perm: False


test:
  batch_size: 1
  num_workers: 0
  log_frequency: 1
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel.MPEG_GPCC_CTC_Solid'
  dataset:
    root: ['datasets/MPEG_GPCC_CTC/Solid']
    filelist_path: ['Solid_1024.txt']
    kd_tree_partition_max_points_num: 0
    with_color: True
    ori_resolution: 1024
    resolution: 1024
