# include "config/convolutional/lossy_coord_v3/kitti.yaml"

train:
  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root: 'datasets/AVC_PCC_CfE_N3908/upload/Cat2A-1/kitti00-10_train'
    coord_scaler: 0.25
    random_flip: True
    morton_sort: True
    morton_sort_inverse: True
    resolution: 30001


test:
  batch_size: 1
  num_workers: 4
  log_frequency: 1
  save_results: True
  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root: 'datasets/AVC_PCC_CfE_N3908/upload/Cat2B-1/kitti11-21_test'
    coord_scaler: 0.25
    morton_sort: False
    resolution: 30001
