model_module_path: models.convolutional.lossy_coord_v3
model:
  num_latents: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  lossl_geo_upsample: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  max_stride: 8192


train:
  rundir_name: 'train_convolutional_<autoindex>'
  more_reproducible: True
  batch_size: 8
  num_workers: 8
  optimizer: AdamW
  momentum: 0.9
  weight_decay: 0.0001
  max_grad_norm: 1.0

  learning_rate: 0.0001
  epochs: 1000

  scheduler: Step
  lr_step_size: 600
  lr_step_gamma: 0.3

  ckpt_frequency: 5
  test_frequency: 0

  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root: 'datasets/AVC_PCC_CfE_N3908/upload/Cat2A-1/Livox_02_all_in_one_1mm/'
    coord_scaler: 0.25
    random_flip: True
    morton_sort: True
    morton_sort_inverse: True
    resolution: 30001


test:
  num_workers: 8
  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root: 'datasets/AVC_PCC_CfE_N3908/upload/Cat2B-1/Livox_02_all_in_one_1mm/'
    coord_scaler: 0.25
    morton_sort: False
    resolution: 30001
