train:
  dataset_path:
    'lib.datasets.PlyVoxel'
  dataset:
    root: 'datasets/8iVFBv2'
    filelist_path: 'list.txt'
    file_path_pattern: '*/Ply/*.ply'

    with_color: False
    with_normal: False
    with_file_path: True

    ori_resolution: 1024
    resolution: 1024
