test:
  dataset_path:
    'lib.datasets.PlyVoxel'
  dataset:
    root: 'datasets/MVUB'
    filelist_path: 'list.txt'
    file_path_pattern: '*9/ply/*.ply'

    with_color: False
    with_normal: False
    with_file_path: True
    with_resolution: True
    with_ori_resolution: True

    ori_resolution: 512
    resolution: 512
