model_path: models.image_compression.baseline


train:
  rundir_name: 'image_compression/<autoindex>'
  more_reproducible: True
  amp: False
  batch_size: 8
  num_workers: 16
  optimizer: Adam
  momentum: 0.9
  weight_decay: 0.0

  learning_rate: 0.0001
  epochs: 10
  lr_step_size: 4
  lr_step_gamma: 0.5

  ckpt_frequency: 1
  test_frequency: 1

  dataset_path: 'lib.datasets.ImageFolder'
  dataset:
    root: 'datasets/OpenImagesV4'
    filelist_path: 'train.txt'
    file_path_pattern: 'train/*.jpg'

    channels_order: 'BGR'
    target_shapes: [768, 512, 512, 768]
    resize_strategy: 'Expand'


test:
  batch_size: 1
  num_workers: 2
  save_results: True
  log_frequency: 1
  dataset_path: 'lib.datasets.ImageFolder'
  dataset:
    root: 'datasets/Kodak'
    filelist_path: 'list.txt'
    file_path_pattern: '*.png'

    channels_order: 'BGR'
    resize_strategy: 'None'
