# include "config/convolutional/lossy_coord_v2/baseline_kitti_r1.yaml"

model:
  skip_encoding_fea: 0
  encoder_channels: [128, 128]
  decoder_channels: [128]
  geo_lossl_if_sample: [1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
  geo_lossl_channels: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 1]


train:
  dataset:
    resolution: 8192


test:
  dataset:
    resolution: 8192
