# include "config/convolutional/lossy_coord_v2/baseline_r3.yaml"

test:
  dataset_module_path:
    'lib.datasets.PlyVoxel.MPEG_GPCC_CTC_Solid_MVUB'
  dataset:
    kd_tree_partition_max_points_num: 600000
