# include "configs/train/convolutional/lossy_coord_v2/baseline.yaml"

model:
  encoder_channels: [16, 64, 128, 128]
  decoder_channels: [128, 64, 16]
  geo_lossl_if_sample: [0, 1, 0, 1, 0, 1, 0, 1]
  geo_lossl_channels: [128, 128, 128, 128, 128, 128, 128, 128, 1]
