# include "config/convolutional/lossl_coord/avs/kitti_ford_livox.yaml"

model:
  skip_top_scales_num: 1


test:
  from_ckpt: weights/convolutional/lossl_coord/avs/kitti_ford_livox.pt
  dataset:
    coord_scaler: 0.5
