# include "config/convolutional/lossl_coord/kitti.yaml"

model:
  max_stride_wo_recurrent: 4096
  max_stride: 16384
  fea_stride: 8
  channels: 256


train:
  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root:
      - 'datasets/AVS_AIPCC_CfE/Cat2A-1/kitti'
      - 'datasets/AVS_AIPCC_CfE/Cat2A-1/Ford_01_AVS_1mm'
      - 'datasets/AVS_AIPCC_CfE/Cat2A-1/Ford_02_AVS_1mm'
      - 'datasets/AVS_AIPCC_CfE/Cat2A-1/Livox_01_all_in_one_1mm'
    coord_scaler: 0.25
    random_flip: True
    morton_sort: True
    morton_sort_inverse: True
    resolution: 30001


test:
  dataset_module_path: 'lib.datasets.PlyVoxel.Base'
  dataset:
    root:
      - 'datasets/AVS_AIPCC_CfE/Cat2B-1/kitti'
      - 'datasets/AVS_AIPCC_CfE/Cat2B-1/Ford_03_AVS_1mm'
      - 'datasets/AVS_AIPCC_CfE/Cat2B-1/Livox_02_all_in_one_1mm'
    coord_scaler: 0.25
    morton_sort: False
    resolution: 30001
