model_module_path: models.convolutional.lossy_coord_v3
model:
  num_latents: [0, 0, 2]
  lossl_geo_upsample: [0, 1, 1]
  max_stride: 64
  coord_recon_loss_factor: 2.0
  warmup_steps: 30000


train:
  rundir_name: 'train_convolutional_<autoindex>'
  batch_size: 8
  num_workers: 8
  optimizer: AdamW
  momentum: 0.9
  weight_decay: 0.0001
  max_grad_norm: 1.0

  ema: True
  ema_warmup: True
  ema_warmup_gamma: 1.0
  ema_warmup_power: 0.75

  learning_rate: 0.0001
  epochs: 50

  scheduler: Step
  lr_step_size: 20
  lr_step_gamma: 0.3

  ckpt_frequency: 5
  test_frequency: 0

  dataset_module_path: 'lib.datasets.ShapeNetCorev2'
  dataset:
    train_filelist_path: 'all_list_obj.txt'
    train_divisions: 'all'
    mesh_sample_points_num: 500000
    mesh_sample_point_method: 'uniform'
    mesh_sample_point_resolution: 256
    random_rotation: True
    morton_sort: True
    morton_sort_inverse: True
    resolution: 128


test:
  num_workers: 4
  dataset_module_path:
    'lib.datasets.PlyVoxel.MPEG_GPCC_CTC_Solid_MVUB'
  dataset:
    kd_tree_partition_max_points_num: [0, 0, 0, 0]
    coord_scaler: [1.0, 1.0, 1.0, 1.0]
