model_path: models.convolutional.baseline
model:
  input_feature_type: 'Occupation'
  basic_block_type: 'InceptionResBlock'
  basic_block_num: 3
  use_batch_norm: False
  activation: 'relu'
  encoder_channels: [16, 32, 64, 32]
  compressed_channels: 8
  decoder_channels: [64, 32, 16]
  reconstruct_loss_type: 'BCE'
  adaptive_pruning: True
  adaptive_pruning_num_scaler: 1.0
  bpp_loss_factor: 0.2


train:
  rundir_name: 'train_convolutional_<autoindex>'
  device: '2,3'
  amp: False
  more_reproducible: True
  batch_size: 24
  num_workers: 4
  optimizer: [Adam, Adam, SGD]
  momentum: 0.9
  weight_decay: [0.0001, 0.0001, 0]
  max_grad_norm: [1.0, 1.0, 0.0]

  learning_rate: [0.0001, 0.0001, 0.0001]
  epochs: 10

  ckpt_frequency: 1
  lr_step_size: 2
  lr_step_gamma: 0.5
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  test_frequency: 4

#  dataset_path: 'lib.datasets.PCGCv2Data'
  dataset_path: 'lib.datasets.ShapeNetCorev2'

  dataset:
    random_rotation: True
    with_resolution: True

test:
  batch_size: 1
  num_workers: 2
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel.Base'
  log_frequency: 1
  dataset:
    with_resolution: True
    with_ori_resolution: True
