model_path: models.convolutional.baseline
model:
  basic_block_type: 'InceptionResBlock'
  basic_block_num: 3
  use_batch_norm: False
  activation: 'relu'
  conv_trans_near_pruning: False
  encoder_channels: [4, 16, 64, 64]
  compressed_channels: 16
  decoder_channels: [64, 16, 4]
  encoder_scaler: 1.0
  hyperprior: 'None'
  hyper_compressed_channels: 16
  prior_indexes_range: [16, 16, 16, 16]
  hyper_encoder_scaler: 1.0
  prior_indexes_scaler: 10.0
  lossless_compression_based: True
  lossless_coder_channels: 64
  lossless_coord_indexes_range: [8, 8, 8, 8]
  lossless_detach_higher_fea: False
  lossless_hybrid_hyper_decoder_fea: True
  bpp_loss_factor: 0.2
  reconstruct_loss_factor: 1.0
  warmup_steps: 1000
  warmup_bpp_loss_factor: 0.01


train:
  rundir_name: 'train_convolutional_<autoindex>'
  device: '2,3'
  amp: False
  more_reproducible: False
  batch_size: 8
  num_workers: 2
  optimizer: [AdamW, AdamW, Adam]
  momentum: 0.9
  weight_decay: [0.0001, 0.0001, 0.0]
  max_grad_norm: [1.0, 1.0, 0.0]

  learning_rate: [0.0005, 0.0001, 0.005]
  epochs: 40

  scheduler: Step
  lr_step_size: 8
  lr_step_gamma: 0.3

  ckpt_frequency: 1
  resume_from_ckpt: ''
  resume_items: ['state_dict']
  test_frequency: 4

  dataset_path: 'lib.datasets.ShapeNetCorev2'
  dataset:
    random_rotation: True
    with_resolution: True


test:
  batch_size: 1
  num_workers: 2
  save_results: True
  dataset_path:
    'lib.datasets.PlyVoxel.Owlii_8iVFBv2'
  log_frequency: 1
  dataset:
    with_resolution: True
    with_ori_resolution: True
